### ISSUE TITLE
All Text is "Editable" and Shows Text Cursor.

### ISSUE THREAD

**Issue by QAEZZ** [tryphotino/photino.NET#173]
**OS:** Arch Rolling (btw :trollface:), this also persists on WSL2.
**WM:** i3
**Display Manager:** LightDM

A friend and I were checking out Photino.NET (very cool, we like it a lot).
We assume GTK is at fault, but we aren't certain.
Everything that has text is a non-editable text box (has a caret) and hovering shows a text cursor.

I've tried CSS to fix this, but could only make the caret transparent, with `cursor: text;` still visible.
CSS attempted:
```css
h1, h2, h3, h4, h5, h6, p, b, strong, i, a, div {
    user-select: none !important;
    -webkit-user-select: none !important;
    caret-color: transparent !important;
    cursor: normal !important; /* Doesn't fix the text cursor */
}
```

This isn't a problem on Windows.
I cannot add a picture as maim hides my cursor when I take a photo.
